services:
  pullpilot:
    container_name: pullpilot
    image: ghcr.io/kernel-nomad/pullpilot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PULLPILOT_PORT:-8000}:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - pullpilot_data:/app/data
      - ${DOCKER_ROOT_PATH}:${DOCKER_ROOT_PATH}
      - ./sessions:/app/sessions
    environment:
      - TZ=${TZ}
      - PROJECTS_ROOT=${DOCKER_ROOT_PATH}

volumes:
  pullpilot_data:
